#Primary color for the interface theme
theme_color = "#78DC77"
#List of post-processing chains to skip injection
inject_post_chain_blacklist = []
#Screen capture mode
capture_mode = "A"
interop_sync_mode = "LowLatency"
#Upscale ratio factor
upscale_ratio = 1.7
#Algorithm used for upscaling
upscale_algo = "fsr1"
#Color scheme variant for the interface theme
theme_scheme_variant = "FIDELITY"
#Contrast level for the interface theme (-1.0 to 1.0)
theme_contrast_level = 0.0
#Disable Super Resolution when using vanilla rendering.
disable_upscale_on_vanilla = false
#This option enables the use of a compatibility shader compiler for compiling shaders when set to true.
compat_shader_compiler = false
#Interface theme
theme = "Light"
#Sharpness adjustment factor
sharpness = 0.55
#Force disable shader pack compatibility mode.
force_disable_shader_compat = false
#Enable super-resolution upscaling
enable_upscale = false
#Pause game when GUI is open
pause_game_on_gui = false
#The precision of the internal texture format affects video memory consumption: higher precision results in greater consumption, while lower precision leads to smaller consumption. Note: Excessively low precision may cause noticeable color banding in the image.
internal_texture_format = "AUTO"

[debug]
	#Skip Vulkan initialization (auto-set based on OS)
	skip_init_vulkan = true
	#Enable RenderDoc integration (auto-disabled on incompatible OS)
	enable_render_doc = false
	#Enable debug mode
	enable_debug = false
	#Enable ImGui debug interface (auto-disabled on incompatible OS)
	enable_imgui = false
	#Dump shaders for debugging purposes
	debug_dump_shader = false
	#Enable more detailed performance profiling for advanced analysis.
	enable_detailed_profiling = false

[optiscaler]
	#Absolute path to the OptiScaler DLL file.
	dll_path = ""
	#Load the selected OptiScaler DLL during early game startup.
	enabled = false

#Algorithm special configuration
[special]

	[special.fsr]
		version = "V2"

	[special.dlss]
		render_preset = "K"

	[special.sgsr2]
		variant = "CS_2"

	[special.fsr1]
		fp16 = true

	[special.fsr2]
		version = "V233"
		fp16 = true

[experiment]
	#Enable experimental features
	enable_experimental_features = false
	#Generate motion vectors for advanced effects
	generate_motion_vectors = false

[dataset]
	dataset_path = "msrDataset"
	enable_dataset_generator = false

