! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! terralith:lavender_forest > aurorasdeco:lavender_plains
! terralith:lavender_valley > aurorasdeco:lavender_plains
! terralith:cave/infested_caves > minecraft:dripstone_caves
! 
! For full biome list, see https://minecraft.wiki/w/Biome#Biome_IDs

terralith:amethyst_canyon > terralith:rocky_mountains
terralith:amethyst_rainforest > terralith:ashen_savanna
terralith:cloud_forest > terralith:rocky_mountains
terralith:lavender_forest > terralith:ashen_savanna
terralith:lavender_valley > terralith:gravel_desert
terralith:moonlight_grove > terralith:gravel_desert
terralith:moonlight_valley > terralith:rocky_mountains
terralith:sandstone_valley > terralith:ashen_savanna
terralith:desert_spires > minecraft:plains
terralith:fractured_savanna > minecraft:dark_forest
terralith:stony_spires > terralith:scarlet_mountains
terralith:skylands > null
terralith:skylands_spring > null
terralith:skylands_summer > null
terralith:skylands_autumn > null
terralith:skylands_winter > null
terralith:haze_mountains > minecraft:plains
terralith:sandstone_slopes > minecraft:plains
terralith:savanna_slopes > minecraft:plains
terralith:scarlet_mountains > terralith:rocky_mountains