#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 27 22:44:03 EEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.2
enableShaders=true
