#Whether to render the floating bats inside the container.
renderBats = true
#Maximum number of bats to render per container (reduces lag on lower end systems).
#Range: 0 ~ 10
maxRenderedBats = 3
#Whether flashbangs temporarily brighten the client lightmap.
flashbangLightmapBoost = true

