
#General Options
[general]
	#Enable / Disables the ability to throw the eye of ender to locate the stronghold structure
	#
	#Default: false
	throwEyeOfEnder = false
	#Enable / Disables the ability to use the eye of ender on the end portal frame blocks
	#
	#Default: false
	useEyeOfEnder = false
	#Enable / Disables the ability to activate the nether portal
	#
	#Default: false
	activateNetherPortal = false
	#Enable / Disables logging debug messages
	#
	#Default: false
	logDebug = false
	#Provide a comma separated list of blocks in the syntax of mod:block
	#
	#Default: minecraft:obsidian,securitycraft:reinforced_obsidian
	activateNetherPortalBlocks = "minecraft:obsidian,securitycraft:reinforced_obsidian"

#World Generation
[worldgen]
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: -1
	generateStronghold = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateRuinedPortal = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateBuriedTreasure = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateDesertPyramid = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateEndCity = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateFortress = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateIgloo = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateJungleTemple = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: -1
	generateMineshaft = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateNetherFossil = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateOceanMonument = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateOceanRuin = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: -1
	generateShipwreck = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateSwampHut = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateWoodlandMansion = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateAncientCity = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateBastionRemnant = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateMansion = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generatePillagerOutpost = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateTrailRuins = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateTrialChambers = 0
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageDesert = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillagePlains = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageSavanna = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageSnowy = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageTaiga = -1
	# Provide a comma separated list of modded structures in the syntax of mod:structure:value
	#
	# mod is the name of the mod
	# structure is the full structure name, partial name ending with *, or only * for all structures in the mod
	# value is one of the following:
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# HINT: Use the /locate structure command to determine the mod and structure names
	generateModdedStructure = "philipsruins:ocean_fortress:0,philipsruins:ocean_ruins:0,philipsruins:lost_soul_city:0,philipsruins:ancient_dungeon:0,philipsruins:ancient_crypt:0,philipsruins:lost_soul_dungeon:0,philipsruins:sculk_dungeon:0,philipsruins:start_nether_dungeon:0,philipsruins:start_nether_ruins:0,bloomingnature:swamp_hut:0,terralith:witch_hut:0,philipsruins:bone_dungeon:0,terralith:mage_tower:0,terralith:spire:0,terralith:underground/frosted_dungeon:0,terralith:mage_complex:0,betterdungeons:skeleton_dungeon:0,betterdungeons:zombie_dungeon:0,betterdungeons:spider_dungeon:0"

